<?xml version="1.0" encoding="UTF-8"?>
<!-- Source: https://github.com/dret/HTML5-overview -->
<!DOCTYPE html5 [
  <!ELEMENT html5 (classdefs, specs, log) >
  <!ELEMENT classdefs (classdef*) >
  <!ELEMENT classdef (#PCDATA) >
  <!ATTLIST classdef
            id ID #REQUIRED
            title CDATA #REQUIRED >
  <!ELEMENT specs (spec*) >
  <!ELEMENT spec (class?, title, abstract) >
  <!ATTLIST spec
            id NMTOKEN #REQUIRED
            status ( WD | CR | PER | PR | REC | NOTE ) #REQUIRED >
  <!ELEMENT class (#PCDATA) >
  <!ATTLIST class
            ref IDREF #REQUIRED >
  <!ELEMENT title (#PCDATA) >
  <!ELEMENT abstract (#PCDATA | q | em)* >
  <!ELEMENT q (#PCDATA) >
  <!ELEMENT em (#PCDATA) >
  <!ELEMENT log (entry*) >
  <!ELEMENT entry (#PCDATA | q | em | a)* >
  <!ATTLIST entry
            date CDATA #REQUIRED >
  <!ELEMENT a (#PCDATA | q)* >
  <!ATTLIST a
            href CDATA #REQUIRED >
]>
<html5>
    <classdefs>
        <classdef id="device" title="Device">Specifications which provide access to the hardware components of the device</classdef>
        <classdef id="media" title="Media">Specifications which provide multimedia functionality (e.g., audio processing)</classdef>
        <classdef id="environment" title="OS Environment">Specifications which provide access to operating system environment (e.g., contacts)</classdef>
        <classdef id="filesystem" title="File System">Specifications to access the local file system such as reading, writing and navigating through it.</classdef>
        <classdef id="graphics" title="Graphics">Graphical specifications. (e.g., canvas)</classdef>
        <classdef id="storage" title="Storage">Specifications to manage or use temporary/persistent storage resources.</classdef>
        <classdef id="DOM" title="DOM">Specifications to access or manipulate the document structure</classdef>
        <classdef id="communications" title="Communications/Networking">Specifications which provide networking-features for communicating and transferring data between clients and servers</classdef>
        <classdef id="security" title="Security">Specifications which provide security features (e.g., hashing, key-management etc.)</classdef>
        <classdef id="monitoring" title="Monitoring">[[ explanation needed ]]</classdef>
        <classdef id="ui" title="User Interaction">[[ explanation needed ]]</classdef>
    </classdefs>
    <specs>
        <spec id="telephony" status="WD">
            <class ref="communications">defines an API to manage telephone calls (e.g dialer app)</class>
            <title>Web Telephony API</title>
            <abstract>This specification defines an API to manage telephone calls. A typical use case of the Web Telephony API is the implementation of a 'Dialer' application supporting multiparty calls and multiple telephony services. A minimal structure for call history items is also defined.</abstract>
        </spec>
        <spec id="discovery-api" status="WD">
            <class ref="communications">[[ explanation needed ]]</class>
            <title>Network Service Discovery</title>
            <abstract>This specification defines a mechanism for an HTML document to discover and subsequently communicate with HTTP-based services advertised via common discovery protocols within the current network.</abstract>
        </spec>
        <spec id="ambient-light" status="WD">
            <class ref="device">provides access to light sensor of an device</class>
            <title>Ambient Light Events</title>
            <abstract>This specification defines a means to receive events that correspond to a light sensor detecting the presence of a light.</abstract>
        </spec>
        <spec id="audioproc" status="WD">
            <class ref="media">[[ explanation needed ]]</class>
            <title>Audio Processing API</title>
            <abstract>This specification introduces and compares two client-side APIs for processing and synthesizing real-time audio streams in the browser.</abstract>
        </spec>
        <spec id="html-picture-element" status="WD">
            <class ref="media">[[ explanation needed ]]</class>
            <title>The picture Element</title>
            <abstract>The picture element is an image container whose source content is determined by one or more CSS media queries.</abstract>
        </spec>
        <spec id="html-longdesc" status="WD">
            <class ref="media">[[ explanation needed ]]</class>
            <title>HTML Image Description Extension</title>
            <abstract>This specification defines a longdesc attribute to link extended descriptions with images in HTML5-based content.</abstract>
        </spec>
        <spec id="html-srcset" status="WD">
            <class ref="media">provides methods to include images in different quality for different viewports (e.g. phones, hq-displays)</class>
            <title>The srcset Attribute</title>
            <abstract>When authors adapt their sites for high-resolution displays, they often need to be able to use different assets representing the same image. We address this need for adaptive, bitmapped content images by adding a srcset attribute to the img element.</abstract>
        </spec>
        <spec id="media-source" status="WD">
            <class ref="media">[[ explanation needed ]]</class>
            <title>Media Source Extensions</title>
            <abstract>This specification extends HTMLMediaElement to allow JavaScript to generate media streams for playback. Allowing JavaScript to generate streams facilitates a variety of use cases like adaptive streaming and time shifting live streams. </abstract>
        </spec>
        <spec id="webmidi" status="WD">
            <class ref="media">[[ explanation needed ]]</class>
            <title>Web MIDI API</title>
            <abstract> Some user agents have connected music devices, such as synthesizers, keyboard and other controllers, and drum machines. The widely adopted Musical Instrument Digital Interface (MIDI) protocol enables electronic musical instruments, controllers and computers to communicate and synchronize with each other. MIDI does not transmit audio signals: instead, it sends event messages about musical notes, controller signals for parameters such as volume, vibrato and panning, cues and clock signals to set the tempo, and system-specific MIDI communications (e.g. to remotely store synthesizer-specific patch data). This same protocol has become a standard for non-musical uses, such as show control, lighting and special effects control. This specification defines an API supporting the MIDI protocol, enabling web applications to enumerate and select MIDI input and output devices on the client system and send and receive MIDI messages. It is intended to enable non-music MIDI applications as well as music ones, by providing low-level access to the MIDI devices available on the users' systems. At the same time, the Web MIDI API is not intended to become a semantic controller platform; it is designed to expose the mechanics of MIDI input and output interfaces, and the practical aspects of sending and receiving MIDI messages, without identifying what those actions might mean semantically. To some users, "MIDI" has become synonymous with Standard MIDI Files and General MIDI. That is not the intent of this API; the use case of simply playing back a .SMF file is not within the purview of this specification (it could be considered a different format to be supported by the HTML5 &lt;audio> element, for example). The Web MIDI API is intended to enable direct access to devices that respond to MIDI - external synthesizers or lighting systems, for example, or even the software synthesizers that are built in to many common operating systems. The Web MIDI API is also explicitly designed to enable a new class of applications on the web that can respond to MIDI controller inputs - using external hardware controllers with physical buttons, knobs and sliders (as well as musical controllers like keyboard, guitar or wind instrument controllers) to control web applications. The Web MIDI API is also expected to be used in conjunction with other APIs and elements of the web platform, notably the Web Audio API and High-Resolution Time. This API is also intended to be familiar to users of MIDI APIs on other systems, such as Apple's CoreMIDI and Microsoft's Windows MIDI API.</abstract>
        </spec>
        <spec id="battery-status" status="CR">
            <class ref="device">provices information about battery status of an device</class>
            <title>Battery Status Event Specification</title>
            <abstract>This specification defines a new DOM event type that provides information about the battery status of the hosting device and associated auxiliary devices.</abstract>
        </spec>
        <spec id="calendar-api" status="WD">
            <class ref="environment">provides access to calender of os-environment</class>
            <title>Calendar API</title>
            <abstract>The Calendar API defines the high-level interfaces required to obtain read access to a user's calendaring service.</abstract>
        </spec>
        <spec id="clipboard-apis" status="WD">
            <class ref="environment">[[ explanation needed ]]</class>
            <title>Clipboard API and Events</title>
            <abstract>This document describes APIs for clipboard operations such as copy, cut and paste in web applications.</abstract>
        </spec>
        <spec id="orientation-event" status="WD">
            <class ref="device">provides information about physical device orientation and motion (for e.g. compass)</class>
            <title>DeviceOrientation Event Specification</title>
            <abstract>This specification defines several new DOM event types that provide information about the physical orientation and motion of a hosting device.</abstract>
        </spec>
        <spec id="app-uri" status="WD">
            <class ref="filesystem">[[ explanation needed ]]</class>
            <title>The app: URI scheme</title>
            <abstract>This specification defines the app: URI scheme and rules for dereferencing an app: URI, which can be used to address resources inside a package (e.g., a packaged application). The dereferencing model relies on HTTP semantics to return resources in a manner akin to a HTTP GET request. Doing so allows this URI scheme to be used with other technologies that rely on HTTP responses to function as intended, such as XmlHttpRequest.</abstract>
        </spec>
        <spec id="FileAPI" status="WD">
            <class ref="filesystem">[[ explanation needed ]]</class>
            <title>File API</title>
            <abstract>This specification provides an API for representing file objects in web applications, as well as programmatically selecting them and accessing their data.</abstract>
        </spec>
        <spec id="file-system-api" status="WD">
            <class ref="filesystem">[[ explanation needed ]]</class>
            <title>File API: Directories and System</title>
            <abstract>This specification defines an API to navigate file system hierarchies, and defines a means by which a user agent may expose sandboxed sections of a user's local filesystem to web applications. It builds on <q>File API: Writer</q>, which in turn built on <q>File API</q>, each adding a different kind of functionality.</abstract>
        </spec>
        <spec id="file-writer-api" status="WD">
            <class ref="filesystem">[[ explanation needed ]]</class>
            <title>File API: Writer</title>
            <abstract>This specification defines an API for writing to files from web applications. This API is designed to be used in conjunction with, and depends on definitions in, other APIs and elements on the web platform. Most relevant among these are <em>File API</em> and <em>Web Workers</em>.</abstract>
        </spec>
        <spec id="fullscreen" status="WD">
            <class ref="ui">provides information about fullscreen capabilities and actions</class>
            <title>Fullscreen</title>
            <abstract>Fullscreen defines the fullscreen API for the web platform.</abstract>
        </spec>
        <spec id="gamepad" status="WD">
            <class ref="ui">specifies interfaces to allow web apps to act on gamepad data</class>
            <title>Gamepad</title>
            <abstract>The Gamepad specification defines a low-level interface that represents gamepad devices.</abstract>
        </spec>
        <spec id="geolocation-API" status="PR">
            <class ref="device">provides access to device geolocation information</class>
            <title>Geolocation API Specification</title>
            <abstract>This specification defines an API that provides scripted access to geographical location information associated with the hosting device.</abstract>
        </spec>
        <spec id="2dcontext" status="WD">
            <class ref="graphics">[[ explanation needed ]]</class>
            <title>HTML Canvas 2D Context</title>
            <abstract>This specification defines the 2D Context for the HTML canvas element.</abstract>
        </spec>
        <spec id="html-media-capture" status="CR">
            <class ref="media">[[ explanation needed ]]</class>
            <title>HTML Media Capture</title>
            <abstract>This specification defines HTML form enhancements that provide access to the audio, image and video capture capabilities of the device.</abstract>
        </spec>
        <spec id="encrypted-media" status="WD">
            <class ref="media">[[ explanation needed ]]</class>
            <title>Encrypted Media Extensions</title>
            <abstract>This proposal extends HTMLMediaElement providing APIs to control playback of protected content. The API supports use cases ranging from simple clear key decryption to high value video (given an appropriate user agent implementation). License/key exchange is controlled by the application, facilitating the development of robust playback applications supporting a range of content decryption and protection technologies. This specification does not define a content protection or Digital Rights Management system. Rather, it defines a common API that may be used to discover, select and interact with such systems as well as with simpler content encryption systems. Implementation of Digital Rights Management is not required for compliance with this specification: only the simple clear key system is required to be implemented as a common baseline. The common API supports a simple set of content encryption capabilities, leaving application functions such as authentication and authorization to page authors. This is achieved by requiring content protection system-specific messaging to be mediated by the page rather than assuming out-of-band communication between the encryption system and a license or other server.</abstract>
        </spec>
        <spec id="microdata" status="WD">
            <title>HTML Microdata</title>
            <abstract>This specification defines the HTML microdata mechanism. This mechanism allows machine-readable data to be embedded in HTML documents in an easy-to-write manner, with an unambiguous parsing model. It is compatible with numerous other data formats including RDF and JSON.</abstract>
        </spec>
        <spec id="webmessaging" status="CR">
            <title>HTML5 Web Messaging</title>
            <abstract>This specification defines two mechanism for communicating between browsing contexts in HTML documents.</abstract>
        </spec>
        <spec id="hr-time" status="REC">
            <class ref="monitoring">[[ explanation needed ]]</class>
            <title>High Resolution Time</title>
            <abstract>This specification defines a JavaScript interface that provides the current time in sub-millisecond resolution and such that it is not subject to system clock skew or adjustments.</abstract>
        </spec>
        <spec id="IndexedDB" status="CR">
	        <class ref="storage">defines APIs for a keys/value database</class>
            <title>Indexed Database API</title>
            <abstract>This document defines APIs for a database of records holding simple values and hierarchical objects. Each record consists of a key and some value. Moreover, the database maintains indexes over records it stores. An application developer directly uses an API to locate records either by their key or by using an index. A query language can be layered on this API. An indexed database can be implemented using a persistent B-tree data structure.</abstract>
        </spec>
        <spec id="media-capture-api" status="NOTE">
            <class ref="media">[[ explanation needed ]]</class>
            <title>Media Capture API</title>
            <abstract>This specification defines an Application Programming Interface (API) that provides access to the audio, image and video capture capabilities of the device.</abstract>
        </spec>
        <spec id="streamproc" status="NOTE">
            <class ref="media">[[ explanation needed ]]</class>
            <title>MediaStream Processing API</title>
            <abstract>A number of existing or proposed features for the Web platform deal with continuous real-time media: HTML media elements, Synchronization of multiple HTML media elements (e.g. proposed HTML MediaController), Capture and recording of local audio and video input (e.g. proposed HTML Streams), Peer-to-peer streaming of audio and video streams (e.g. proposed WebRTC and HTML Streams), and Advanced audio APIs that allow complex mixing and effects processing (e.g. Mozilla's AudioData, Chrome's AudioNode). Many use-cases require these features to work together. This proposal makes HTML Streams the foundation for integrated Web media processing by creating a mixing and effects processing API for HTML Streams.</abstract>
        </spec>
        <spec id="mediastream-recording" status="WD">
            <class ref="media">[[ explanation needed ]]</class>
            <title>MediaStream Recording</title>
            <abstract>This document defines a recording API for use with MediaStreams as defined in Media Capture and Streams.</abstract>
        </spec>
        <spec id="image-capture" status="WD">
            <class ref="media">[[ explanation needed ]]</class>
            <title>Mediastream Image Capture</title>
            <abstract>This document specifies the takePhoto() and getFrame() methods, and corresponding camera settings for use with MediaStreams as defined in Media Capture and Streams.</abstract>
        </spec>
        <spec id="streams-api" status="WD">
            <title>Streams API</title>
            <abstract>This specification provides an API for representing binary data in web applications as a Stream object, as well as programmatically building and reading its contents. This includes: A Stream interface, which represents a sequence of data that can be read over time; A StreamReader interface, which provides methods to read the contents of a Stream as a Blob, DataURL, ArrayBuffer, or as Text; A StreamBuilder interface, which allows for creating a new Stream whose contents is read from an internal buffer that was made by appending Text, Blobs, or ArrayBuffers; Extensions to XmlHttpRequest to add support for upload and download of a Stream; Extensions to createObjectURL and revokeObjectURL to add support for Stream. Additionally, this specification defines objects to be used within threaded web applications for the synchronous reading of a Stream. This API is designed to be used in conjunction with other APIs and elements on the web platform, notably: File, XMLHttpRequest (e.g. with an overloaded send() method and response object for Stream objects), postMessage, and Web Workers.</abstract>
        </spec>
        <spec id="messaging-api" status="WD">
            <class ref="communications">[[ explanation needed ]]</class>
            <title>The Messaging API</title>
            <abstract>This specification defines an API that provides access to messaging functionality in the device, including SMS, MMS and email.</abstract>
        </spec>
        <spec id="messaging" status="WD">
            <class ref="communications">[[ explanation needed ]]</class>
            <title>Messaging API</title>
            <abstract>This specification defines a System Level API which offers a simple interface to get access to mobile messaging services. A typical use case of the Messaging API is the implementation of a messaging client application that allows the user to send SMS and MMS messages as well as to access and manage the received SMS and MMS messages.</abstract>
        </spec>
        <spec id="navigation-timing" status="REC">
            <class ref="monitoring">[[ explanation needed ]]</class>
            <title>Navigation Timing</title>
            <abstract>This specification defines an interface for web applications to access timing information related to navigation and elements.</abstract>
        </spec>
        <spec id="navigation-timing-2" status="WD">
            <class ref="monitoring">[[ explanation needed ]]</class>
            <title>Navigation Timing 2</title>
            <abstract>This specification defines a unified interface to store and retrieve high resolution performance metric data related to the navigation of a document.</abstract>
        </spec>
        <spec id="page-visibility" status="REC">
            <class ref="monitoring">[[ explanation needed ]]</class>
            <title>Page Visibility</title>
            <abstract>This specification defines a means for site developers to programmatically determine the current visibility state of the page in order to develop power and CPU efficient web applications.</abstract>
        </spec>
        <spec id="performance-timeline" status="CR">
            <class ref="monitoring">[[ explanation needed ]]</class>
            <title>Performance Timeline</title>
            <abstract>This specification defines an interface for web applications to access timing information related to navigation and elements.</abstract>
        </spec>
        <spec id="gallery" status="WD">
            <class ref="media">[[ explanation needed ]]</class>
            <title>Pick Media Intent</title>
            <abstract>The Pick Media Intent defines a Web Intent that enables access to a user's media gallery from inside a Web application. It defines both an Intent action/type pair that selects this operation, and the format of the media data that is returned by services implementing this specification. </abstract>
        </spec>
        <spec id="pointerlock" status="WD">
            <title>Pointer Lock</title>
            <abstract>This specification defines an API that provides scripted access to raw mouse movement data while locking the target of mouse events to a single element and removing the cursor from view. This is an essential input mode for certain classes of applications, especially first person perspective 3D applications and 3D modelling software.</abstract>
        </spec>
        <spec id="ime-api" status="WD">
            <class ref="ui">[[ explanation needed ]]</class>
            <title>IndieUI: Events 1.0</title>
            <abstract>IndieUI: Events 1.0 is an abstraction between physical, device-specific user interaction events and inferred user intent such as scrolling or changing values. This provides an intermediate layer between device- and modality-specific user interaction events, and the basic user interface functionality used by web applications. IndieUI: Events focuses on granular user interface interactions such as scrolling the view, canceling an action, changing the value of a user input widget, selecting a range, placing focus on an object, etc. Implementing platforms will combine modality-specific user input, user idiosyncratic heuristics to determine the specific corresponding Indie UI event, and send that to the web application in addition to the modality-specific input such as mouse or keyboard events, should applications wish to process it.</abstract>
        </spec>
        <spec id="indie-ui-events" status="WD">
            <class ref="ui">[[ explanation needed ]]</class>
            <title>Input Method Editor API</title>
            <abstract>This specification defines an "IME API" that provides Web applications with scripted access to an IME (input-method editor) associated with a hosting user agent. This IME API includes: an InputMethodContext interface, which provides methods to retrieve detailed data from an in-progress IME composition; and a Composition dictionary, which represents read-only attributes about the current composition, such as the actual text and its style. This API is designed to be used in conjunction with DOM events.</abstract>
        </spec>
        <spec id="DataCache" status="NOTE">
            <title>Programmable HTTP Caching and Serving</title>
            <abstract>This document defines APIs for off-line serving of requests to HTTP resources using static and dynamic responses. It extends the function of application caches defined in HTML5.</abstract>
        </spec>
        <spec id="proximity" status="WD">
            <class ref="device">provides access to proximity sensor of an device</class>
            <title>Proximity Events</title>
            <abstract>This specification defines a means to receive events that correspond to a proximity sensor detecting the presence of a physical object. </abstract>
        </spec>
        <spec id="quota-api" status="WD">
            <class ref="storage">defines an API to query, manage usage and availability of a user's local storage</class>
            <title>Quota Management API</title>
            <abstract>This specification defines an API to manage usage and availability of local storage resources, and defines a means by which a user agent (UA) may grant Web applications permission to use more local space, temporarily or persistently, via various different storage APIs.</abstract>
        </spec>
        <spec id="resource-timing" status="CR">
            <class ref="monitoring">[[ explanation needed ]]</class>
            <title>Resource Timing</title>
            <abstract>This specification defines an interface for web applications to access timing information related to HTML elements.</abstract>
        </spec>
        <spec id="screen-orientation" status="WD">
            <class ref="device">provides access to device screen orientation (portrait/landscape)</class>
            <title>Screen Orientation API</title>
            <abstract>The Screen Orientation API's goal is to provide an interface for web applications to be able to read the screen orientation state, to be informed when this state changes and to be able to lock the screen orientation to a specific state.</abstract>
        </spec>
        <spec id="selectors-api" status="WD">
            <class ref="DOM">[[ explanation needed ]]</class>
            <title>Selectors API Level 1</title>
            <abstract>The Selectors API specification defines methods for retrieving Element nodes from the DOM by matching against a group of selectors.</abstract>
        </spec>
        <spec id="selectors-api2" status="WD">
            <class ref="DOM">[[ explanation needed ]]</class>
            <title>Selectors API Level 2</title>
            <abstract>The Selectors API specification defines methods for retrieving element nodes from the DOM by matching against a group of selectors, and for testing if a given element matches a particular selector.</abstract>
        </spec>
        <spec id="domparsing" status="WD">
            <class ref="DOM">[[ explanation needed ]]</class>
            <title>DOM Parsing and Serialization</title>
            <abstract>This specification defines various APIs for programmatic access to HTML and generic XML parsers by web applications for use in parsing and serializing DOM nodes.</abstract>
        </spec>
        <spec id="html-templates" status="WD">
            <class ref="DOM">[[ explanation needed ]]</class>
            <title>HTML Templates</title>
            <abstract>This specification describes a method for declaring inert DOM subtrees in HTML and manipulating them to instantiate document fragments with identical contents.</abstract>
        </spec>
        <spec id="shadow-dom" status="WD">
            <class ref="DOM">[[ explanation needed ]]</class>
            <title>Shadow DOM</title>
            <abstract>This specification describes a method of establishing and maintaining functional boundaries between DOM trees and how these trees interact with each other within a document, thus enabling better functional encapsulation within the DOM.</abstract>
        </spec>
        <spec id="custom-elements" status="WD">
            <class ref="DOM">[[ explanation needed ]]</class>
            <title>Custom Elements</title>
            <abstract>This specification describes the method for enabling the author to define and use new types of DOM elements in a document.</abstract>
        </spec>
        <spec id="html-imports" status="WD">
            <class ref="DOM">[[ explanation needed ]]</class>
            <title>HTML Imports</title>
            <abstract>HTML Imports are a way to include and reuse HTML documents in other HTML documents.</abstract>
        </spec>
        <spec id="eventsource" status="CR">
            <class ref="communications">[[ explanation needed ]]</class>
            <title>Server-Sent Events</title>
            <abstract>This specification defines an API for opening an HTTP connection for receiving push notifications from a server in the form of DOM events. The API is designed such that it can be extended to work with other push notification schemes such as Push SMS.</abstract>
        </spec>